<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-UH1VAF7" name="OrangehrmTestscripts.verifyAssert" tests="1" failures="1" timestamp="7 Nov 2017 15:58:17 GMT" time="14.922" errors="0">
  <testcase name="login" time="14.922" classname="OrangehrmTestscripts.verifyAssert">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [The password you have entered is incorrect.Your Account will be deactivated after 2 invalid login attempts] but found [The password you have entered is incorrect.Your Account will be deactivated after 2 invalid login attempts.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [The password you have entered is incorrect.Your Account will be deactivated after 2 invalid login attempts] but found [The password you have entered is incorrect.Your Account will be deactivated after 2 invalid login attempts.]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at OrangehrmTestscripts.verifyAssert.login(verifyAssert.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- OrangehrmTestscripts.verifyAssert -->
